server:
  url: ${server.address:http://localhost}:${server.port}
  address: ${HOSTNAME:localhost}
  port: 8080
  shutdown: graceful

spring:
  application:
    name: payment-dynamodb

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: us-east-1
    secretKey: dummy-secret-key
    accessKey: dummy-secret-key

logging:
  level:
    root: info

