apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-localstack
spec:
  selector:
    app: localstack
  ports:
    - port: {{ .Values.localstack.port }}
      targetPort: {{ .Values.localstack.port }}
  type: ClusterIP