package com.github.fabriciolfj.payment_dynamodb.application.repositories.card

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*
import java.math.BigDecimal
import java.time.Instant

@DynamoDbBean
data class PaymentCardData(
    @get:DynamoDbPartitionKey
    @get:DynamoDbSecondarySortKey(indexNames = ["xie_paymentcard_by_customer"])
    var code: String? = null,
    @get:DynamoDbSecondaryPartitionKey(indexNames = ["xie_paymentcard_by_customer"])
    @get:DynamoDbAttribute(value = "customerId")
    var customerId: String? = null,
    var value: BigDecimal? = null,
    var flag: String? = null,
    var type: String? = null,
    @get:DynamoDbSecondaryPartitionKey(indexNames = ["xie_paymentcard_by_identifier"])
    var identifier: String? = null,
    var status: String? = null,
    var installments: Int = 0,
    var datePayment: Instant? = null,
    @get:DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @get:DynamoDbAutoGeneratedTimestampAttribute
    var createAt: Instant? = null,
    @get:DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)
    @get:DynamoDbAutoGeneratedTimestampAttribute
    var updateAt: Instant? = null
)