package com.github.fabriciolfj.payment_dynamodb.application.repositories.card

import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior
import java.math.BigDecimal
import java.time.Instant

@DynamoDbBean
data class PaymentCardData(
    @get:DynamoDbPartitionKey
    @get:DynamoDbSecondarySortKey(indexNames = ["xie_paymentcard_by_customer"])
    val code: String? = null,
    @get:DynamoDbSecondaryPartitionKey(indexNames = ["xie_paymentcard_by_customer"])
    val customer: String? = null,
    val value: BigDecimal? = null,
    val flag: String? = null,
    val type: String? = null,
    @get:DynamoDbSecondaryPartitionKey(indexNames = ["xie_paymentcard_by_identifier"])
    val identifier: String? = null,
    val status: String? = null,
    @get:DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @get:DynamoDbAutoGeneratedTimestampAttribute
    val createAt: Instant? = null,
    @get:DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)
    @get:DynamoDbAutoGeneratedTimestampAttribute
    val updateAt: Instant? = null
)